### ISSUE TITLE
Optional basic auth support

### ISSUE THREAD

**Issue by Jrchintu** [SharzyL/pastebin-worker#11]
I am currently using this pastebin privately but sometime when i share the link in some groups, suddenly it lead to abuse of pastebin.

If possible, a optional basic auth can help in such case.

Same concept of basic auth has been used here https://github.com/maple3142/GDIndex

**Comment by SharzyL** [comment]
For convenience we can simply use HTTP basic auth. The auth is triggered on `index.html` and all non-GET request. `config.json` should contain a list of `user : hash_of_password` pair. Cloudflare provides part of crypto API to compute hash. 

Sorry but I am busy these days. Thus it may take a few weeks until it is implemented. Or it will be of great help if you may submit a PR on this.

**Comment by Jrchintu** [comment]
> 

Thanks for your quick response. Sorry to inform but i have no experties in web development. I have no issue about time, you can do it anytime, at the end its your project.

Also thanks for this awesome project

**Comment by Jrchintu** [comment]
sorry, i had accidentally closed it last time

**Comment by SharzyL** [comment]
Try the experimental branch https://github.com/SharzyL/pastebin-worker/tree/basic-auth. If it is tested OK, the branch will soon be merged to master

**Comment by Jrchintu** [comment]
Hello @DarremMolko have you succeed to have basic auth ? If so please consider reporting to sharzyl, unfortuantely i am unable to test it.
Thanks

**Comment by DarremMolko** [comment]
> Hello @DarremMolko have you succeed to have basic auth ? If so please consider reporting to sharzyl, unfortuantely i am unable to test it. Thanks

Yes, it works perfectly fine (I made some tests with the API and in the website). I think it's good enough to be merged.

**Comment by DarremMolko** [comment]
The changes are explained in the readme of the basic-auth branch (https://github.com/SharzyL/pastebin-worker/blob/basic-auth/README.md#auth). Here are some screenshots:
![IMG_20220712_172304_319](https://user-images.githubusercontent.com/70179709/178589370-e56317c5-a228-47a5-8758-ed0558679f3a.jpg)
![IMG_20220712_172311_643](https://user-images.githubusercontent.com/70179709/178589406-950e30dd-651b-448f-ad26-d3486561e4a7.jpg)

**Comment by Jrchintu** [comment]
> The changes are explained in the readme of the basic-auth branch (https://github.com/SharzyL/pastebin-worker/blob/basic-auth/README.md#auth). Here are some screenshots: ![IMG_20220712_172304_319](https://user-images.githubusercontent.com/70179709/178589370-e56317c5-a228-47a5-8758-ed0558679f3a.jpg) ![IMG_20220712_173650_297](https://user-images.githubusercontent.com/70179709/178590691-d1cdefd6-958b-483e-a79c-0bc4dd479ae7.jpg)

Oh, ok that looks good. Thanks @SharzyL for adding this feature & @DarremMolko for testing. Since this issue has been fixed, i consider closing this issue
