### ISSUE TITLE
Suggestion: option to use as link shortner

### ISSUE THREAD

**Issue by Jrchintu** [SharzyL/pastebin-worker#12]
We can add an option which will redirect to the url pasted in pastebin. I have no idea how to implement it (sorry for that, i have no prior knowledge). But i found some of projects of url shortner based on cloudflare workers that may help:
https://github.com/dewanshchaudhari/url-shortner
https://github.com/hashirahmad/cloudflareWorkersUrlShortner

Thanks for this pastebin.

**Comment by SharzyL** [comment]
This feature has already been implemented. For example if you have a paste that can be accessed by `shz.al/abcd`, then `shz.al/u/abcd` will redirect you the the URL in the paste.
