### ISSUE TITLE
[Question] how to post file with pb (bash script)

### ISSUE THREAD

**Issue by Bugaddr** [SharzyL/pastebin-worker#13]
I had tried -f option:
`pb p -f filename.sh`

But it throws error:
`redundant arguments '--'`

**Comment by SharzyL** [comment]
There should be some bug in pb script. Before the bug is fixed, you can use `pb p filename.sh` to post file.

**Comment by Bugaddr** [comment]
> There should be some bug in pb script. Before the bug is fixed, you can use `pb p filename.sh` to post file.

Thanks, it works. Will wait for the fir 👍👍
