### ISSUE TITLE
Is there any detailed deployment tutorial?

### ISSUE THREAD

**Issue by 227575** [SharzyL/pastebin-worker#26]
I tried Fork and changed the corresponding data. The webpage could not find the server and the custom domain was invalid. Is there any detailed tutorial? I searched for an article but failed.

**Comment by SharzyL** [comment]
Is the custom domain linked to your Cloudflare account?

Besides, it would be helpful if you could provide a list of commands and logs during your deployment.

**Comment by SharzyL** [comment]
May I have a look at the log when you run `make deploy`? You could mask out sensitive information for privacy.

**Comment by SharzyL** [comment]
Take a look at the GitHub Action log. I guess you have not set the CF_API_TOKEN and CF_ACCOUNT_ID secrets.

**Comment by SharzyL** [comment]
The best reference is README.md since it is always updated.

If you do not know how to set GitHub Action secrets, refer to README.md and deploy manually.

**Comment by SharzyL** [comment]
The deployment documentation is rewritten now. It should be much simpler than before.
