### ISSUE TITLE
[Feature Request] Support custom url in pb script

### ISSUE THREAD

**Issue by sainnhe** [SharzyL/pastebin-worker#34]
Thanks for creating this awesome pastebin!

When I'm using the `pb` script, I found that the domain is hardcoded:

https://github.com/SharzyL/pastebin-worker/blob/8e7fbf57b5ec31fc73ad5b17edf2e24511b684db/scripts/pb#L1-L3

Is it possible to add an option to allow using custom domain so users can use their own instance? Thanks in advance!

**Comment by SharzyL** [comment]
Have a look at #35. It looks inconvinient to me to specify the domain each time using the script. So I do not prefer specifying the domain via cmd args. The PR will be merged if you find it OK.

**Comment by sainnhe** [comment]
> It looks inconvinient to me to specify the domain each time using the script.

I agree. IMO the PR looks good. Thank you!
