### ISSUE TITLE
Private deployment failed and New function wanted

### ISSUE THREAD

**Issue by GOgo8Go** [SharzyL/pastebin-worker#43]
Thanks for providing this great project.

(1).Pls help, I have a problem with private deployment:

    1. I add the following entry to the wrangler.toml (same as the following code).
        [vars.BASIC_AUTH]
        user1 = "passwd1"
        user2 = "passwd2"
    
    2. The github action build it, but failed, which says:
    -----------------------------------------[2/14]-----------------------------------------

     FAIL  test/basic.spec.js > expire
    AssertionError: expected 401 to strictly equal 200

    - Expected
    + Received

    - 200
    + 401

     >Module.upload test/testUtils.js:28:33

    Error: AssertionError: expected 401 to strictly equal 200

     >Module.upload test/testUtils.js:28:33
     >testExpireParse test/basic.spec.js:122:26
     >test/basic.spec.js:126:3

         26|     body: createFormData(kv),
         27|   }))
         28|   expect(uploadResponse.status).toStrictEqual(200)
           |                                 ^
         29|   expect(uploadResponse.headers.get("Content-Type")).toStrictEqual("ap…
         30|   return JSON.parse(await uploadResponse.text())
     >testExpireParse test/basic.spec.js:122:26
     >test/basic.spec.js:126:3
     
     Error: AssertionError: expected 401 to strictly equal 200

    - Expected
    + Received

    - 200
    + 401

     > Module.upload test/testUtils.js:28:33
     > test/pages.spec.js:62:16

         26|     body: createFormData(kv),
         27|   }))
         28|   expect(uploadResponse.status).toStrictEqual(200)
           |                                 ^
         29|   expect(uploadResponse.headers.get("Content-Type")).toStrictEqual("ap…
         30|   return JSON.parse(await uploadResponse.text())
     > test/pages.spec.js:62:16

    ----------------------------------------[14/14]-

    
    3. if not add the entry to the wrangler.toml, the github action can build it successfully, and the project will run successfully in Cloudflare.
    
    So, how can I solve this problem? Or what else should I do?
    
(2).New function wanted: To be more private!

Now if we have a paste, like: https://shz.al/5555, we open this url in the browser, it shows every word we pasted.

    1.Can we make it more private, letting it shows "nothing" in browser, by encoding like with ISO-2022-CN.
    2.While, if request from other clients who encode it with utf8, the client will get the correct data.
    3.and we set a password 8888, like https://shz.al/55558888, it will encode with utf8, if open in browser, we can see the correct data again.
    4.I know the url https://shz.al/5555:8888 is the Admin URL.

Thanks again

**Comment by SharzyL** [comment]
For the firist problem, you can simply delete the tests in GitHub Actions.

https://github.com/SharzyL/pastebin-worker/blob/b0cc58e4715c7fa5d43b7ee9f7bbdc40ab1a286b/.github/workflows/deploy.yml#L22-L23

For the second problem, you can choose a longer paste URL to archive the same goal.

**Comment by GOgo8Go** [comment]
Thank you very much for your reply.

1. The first problem was solved.
2. Still have the second problem, I tried the long random UR, and also set myself as long as 300 characters long for the url, it still shows every word I pasted when open in the browser.

**Comment by SharzyL** [comment]
> it still shows every word

I am a bit confused. What do you want it to show? Can you explain it in more detail or give some example?

**Comment by GOgo8Go** [comment]
Say, if we have a paste url, for example: https://shz.al/anHT, when we open this url in the browser, it shows every word we pasted inside.  It's visible.
![1](https://github.com/SharzyL/pastebin-worker/assets/153721248/7edbc088-b635-4a39-8adf-7ced2f0f9f26)

What I need is that:
1. let the words not visible when open in browser, maybe by encoding like with ISO-2022-CN.
![2](https://github.com/SharzyL/pastebin-worker/assets/153721248/bdf97b66-539a-489e-ad88-40d8feb1568e)
 Want it invisible like this.
 But if other client send request and encode with utf8, the client will get the correct data.

2.And if we open the url with password, it can be visible again by encoding with utf8 in browser, like https://shz.al/anHT8888

**Comment by GOgo8Go** [comment]
.
