### ISSUE TITLE
`yarn wrangler kv:key list` command needs `-s` option in README.md

### ISSUE THREAD

**Issue by ak1ra-komj** [SharzyL/pastebin-worker#54]
The `-s, --silent` option needs to be added to the List pastes command in README.md, otherwise `yarn` outputs additional console logs in the standard output, so that the `kv_list.json` is not a valid .json file, i.e.

> `$ yarn -s wrangler kv:key list --binding PB > kv_list.json`

By the way, I'd like to add two `jq` examples for reference,

```shell
# list pastes and convert to ~/.local/pb_hist format using jq
yarn -s wrangler kv:key list --binding PB |
    jq -r '.[] | "\(.name):\(.metadata.passwd)"'

# list pastes and convert to curl -XDELETE command using jq
yarn -s wrangler kv:key list --binding PB |
    jq -r '.[] | "curl -XDELETE https://shz.al/\(.name):\(.metadata.passwd)"'
```

**Comment by SharzyL** [comment]
Fixed in 2e26036844a58c38beff00733061bfe55fb176b8. Your examples seem not to fit into common administration scenario hence I found nowhere to place them.

**Comment by ak1ra-komj** [comment]
I added `list-pastes` and two more jq examples to `package.json` in my [selfhost branch](https://github.com/ak1ra-lab/pastebin-worker/commit/f421f81d38865ed273459648ba96295be5532c5b), since `delete-paste` is already there, but it's a bit "dirty" so I didn't directly submit a PR,

```
$ git diff HEAD~
package.json --- JSON
10 10     "dev": "wrangler dev --var BASE_URL:http://localhost:8787 --port 8787",
11 11     "build": "wrangler deploy --dry-run --outdir=dist",
12 12     "delete-paste": "wrangler kv:key delete --binding PB",
.. 13     "list-pastes": "wrangler kv:key list --binding PB",
.. 14     "pb_hist": "wrangler kv:key list --binding PB | jq -r '.[] | \"\\(.name):\\(.metadata.passwd)\"'",
.. 15     "curl-delete": "wrangler kv:key list --binding PB | jq -r '.[] | \"curl -XDELETE https://komj.uk/\\(.name):\\(.metadata.passwd)\"'",
13 16     "test": "vitest",
14 17     "coverage": "vitest run --coverage"
15 18   },
```

If you feel this is ok, then I can submit a new PR, if don't, I'll just keep it in my selfhost branch.

**Comment by SharzyL** [comment]
I am still looking for a better administration panel and these commands do not quite fit my need. So let's see it later.
